apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mdhack/solar-system:13-e9e8960a530ef0fece24338a13c6bdea0a55b73a
        name: solar-system
        ports: 
        - containerPort: 80
