apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mdhack/solar-system:11-835ae872dc17688327bd3de022a5b386e4e74164
        name: solar-system
        ports: 
        - containerPort: 80
